---
- hosts: student
  tasks:
  - name: wait until the file is present
    wait_for: 
      path: "/tmp/test.log"
      timeout: 15
      delay: 10         
  - debug:
      msg: "OK-1"
  - debug:
      msg: "OK-2"
