---
- hosts: localhost
  tasks:
  - debug: msg="OK-1"
    notify: callme
  - debug: msg="OK-2"
  - debug: msg="OK-3"
  - debug: msg="OK-4"
  handlers:
  - name: callme
    debug: msg="This is Handler block"
