---
- name: yml to json format
  hosts: localhost
  tasks:
  - copy: 
     content: "{{ansible_facts|to_json}}"
     dest: /tmp/p1.json
  - name: task2
    command: cat /tmp/p1.json
    register: result
  - set_fact: r="{{result.stdout|from_json}}"
  - debug: var=r
