---
- hosts: webservers
  vars:
  - rhpkg: httpd
  - dbpkg: apache2
  tasks:
  - yum: name="{{rhpkg}}" state=installed
    when: ansible_os_family == "RedHat"
  - apt: name="{{dbpkg}}" state=present
    when: ansible_os_family == "Debian"
